config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  resources :candidates do
    member do
      post :vote
    end
  end

  root to: "candidates#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/candidate.rb
class Candidate < ApplicationRecord
  has_many :vote_logs, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :vote_log      
end

app/models/vote_log.rb
class VoteLog < ApplicationRecord
  belongs_to :candidate,counter_cache: true
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :exception
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController
  before_action :find_candidate, only: [:edit, :update, :destroy, :vote]
  before_action :authenticate_user!, only: [:edit, :update, :new, :destroy ,:vote]

  def index
    @candidates = Candidate.all
  end

  def new
    @candidate = Candidate.new

  end

  def create
    @candidate = Candidate.new(candidate_params)
    if @candidate.save
      # 成功
      redirect_to candidates_path, notice: "新增候選人成功!"
    else
      # 失敗
      render :new
    end
  end

  def edit

  end

  def update
    if @candidate.update(candidate_params)
      # 成功
      redirect_to candidates_path, notice: "資料更新成功!"
    else
      # 失敗
      render :edit
    end
  end

  def destroy
    @candidate.destroy if @candidate
    redirect_to candidates_path, notice: "候選人資料已刪除!"
  end

  def vote
    vote = VoteLog.find_by user_id: current_user
    if vote.nil?
      @candidate.vote_logs.create(user: current_user) if @candidate
      redirect_to candidates_path, notice: "完成投票!"
    else
      redirect_to candidates_path, alert: "您已經投過票了!"
    end
    
  end

  private
    def candidate_params
      params.require(:candidate).permit(:department, :grade, :name, :sex, :position, :reason, :politics)
    end

    def find_candidate
        @candidate = Candidate.find_by(id: params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/candidates_helper.rb
module CandidatesHelper
  def isAdmin?(email)
    email.eql? "admin@ntub.edu.tw"           
  end

end

app/views/candidates/_form.html.erb
 <%= simple_form_for(candidate)  do |f| %>
    
    <%= f.input :department, required: true, label:"科系", :collection => [['會計資訊系', '會計資訊系'], ['財政稅務系', '財政稅務系'],['國際商務系','國際商務系'],['企業管理系','企業管理系'],['資訊管理系','資訊管理系'],['應用外語系','應用外語系']] %>

    <%= f.input :grade, required: true, label:"年級", :collection => [['五專一', '五專一'], ['五專二', '五專二'],['五專三','五專三'],['五專四','五專四'],['五專五','五專五'],['四技一','四技一'],['四技二','四技二'],['四技三','四技三'],['四技四','四技四'],['二技一','二技一'],['二技二','二技二']]  %>
 
    <%= f.input :name , required: true, label: "參選人姓名", required: true %>

    <%= f.input :sex, required: true, label:"性別", :collection => [['男', '男'], ['女', '女']] %>
   
    <%= f.input :position, required: true, label:"參選職位" %>

    <%= f.input :reason, required: true, label:"參選原因" %>

    <%= f.input :politics, required: true, label: "參選政見" %>

    <%= f.submit  %>
  <% end %>

app/views/candidates/edit.html.erb
<h1>修改候選人</h1>

<%= render "form", candidate: @candidate %>

<br />
<%= link_to '回候選人列表', candidates_path %>

app/views/candidates/index.html.erb
<nav>
  <% unless user_signed_in? %>
    <%= link_to "註冊", new_user_registration_path %>
    <%= link_to "登入", new_user_session_path %>  
  <% end %> 
  <% if user_signed_in? %>
    <%= current_user.name %>您好!
    <%= link_to "登出", destroy_user_session_path, method: :delete %>
  <% end %>
</nav>

<h1>候選人列表</h1>
  <% if user_signed_in? %>
    <% if isAdmin?(current_user.email) %>
      <%= link_to "新增候選人", new_candidate_path %>
    <% end %>
  <% end %>
  <table class="table">
    <thead>
      <tr>
        <td>投票</td>
        <td>系科</td>
        <td>年級</td>
        <td>參選人姓名</td>
        <td>性別</td>
        <td>參選職位</td>
        <td>參選原因</td>
        <td>參選政見</td>
        <td>得票數</td>
        <% if user_signed_in? %>
          <% if isAdmin?(current_user.email) %>
            <td>處理</td>
          <% end %>
        <% end %>
      </tr>
    </thead>
    <tbody>
      <% @candidates.each do |candidate| %>
      <tr>
        <td><%= link_to "投給這位", vote_candidate_path(candidate), method: "post", data: { confirm: "確定投給這個人?" }, class:"btn btn-danger btn-xs" %></td>
        <td><%= candidate.department %></td>
        <td><%= candidate.grade %></td>
        <td><%= candidate.name %></td>
        <td><%= candidate.sex %></td>
        <td><%= candidate.position %></td>
        <td><%= candidate.reason %></td>
        <td><%= candidate.politics %></td>
        <td><%= candidate.vote_logs.size %></td>
        <% if user_signed_in? %>
          <% if isAdmin?(current_user.email) %>
            <td>
              <%= link_to "編輯", edit_candidate_path(candidate) %>
              <%= link_to "刪除", candidate_path(candidate), method: "delete", data: { confirm: "確認刪除" } %>
            </td>
          <% end %>
        <% end %>
      </tr>
      <% end %>
    </tbody>
  </table>

app/views/candidates/new.html.erb
<h1>新增候選人</h1>

<%= render "form", candidate: @candidate %>

<br />
<%= link_to '回候選人列表', candidates_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StudentLeaderVote</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>